In [1]:
import pandas as pd

In [3]:
df = pd.read_csv(r'''C:\Users\MiaZo_000\Desktop\LoanData.csv''',skiprows=1)

C:\Users\MiaZo_000\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:2698: DtypeWarning: Columns (0,47) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 42542 entries, 0 to 42541
Columns: 145 entries, id to settlement_term
dtypes: float64(115), object(30)
memory usage: 47.1+ MB

In [6]:
df.select_dtypes(exclude='O').describe().T

,count,mean,std,min,25%,50%,75%,max
member_id,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
loan_amnt,42535.0,11089.722581,7410.938391,500.00,5200.000000,9700.000000,15000.000000,3.500000e+04
funded_amnt,42535.0,10821.585753,7146.914675,500.00,5000.000000,9600.000000,15000.000000,3.500000e+04
funded_amnt_inv,42535.0,10139.938785,7131.598014,0.00,4950.000000,8500.000000,14000.000000,3.500000e+04
installment,42535.0,322.623063,208.927216,15.67,165.520000,277.690000,428.180000,1.305190e+03
annual_inc,42531.0,69136.556420,64096.349719,1896.00,40000.000000,59000.000000,82500.000000,6.000000e+06
url,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
dti,42535.0,13.373043,6.726315,0.00,8.200000,13.470000,18.680000,2.999000e+01
delinq_2yrs,42506.0,0.152449,0.512406,0.00,0.000000,0.000000,0.000000,1.300000e+01
inq_last_6mths,42506.0,1.081424,1.527455,0.00,0.000000,1.000000,2.000000,3.300000e+01
mths_since_last_delinq,15609.0,35.017618,22.418427,0.00,17.000000,33.000000,51.000000,1.200000e+02
mths_since_last_record,3651.0,59.175568,47.145396,0.00,0.000000,85.000000,101.000000,1.290000e+02
open_acc,42506.0,9.343951,4.496274,1.00,6.000000,9.000000,12.000000,4.700000e+01
pub_rec,42506.0,0.058156,0.245713,0.00,0.000000,0.000000,0.000000,5.000000e+00
revol_bal,42535.0,14297.860915,22018.441010,0.00,3635.000000,8821.000000,17251.000000,1.207359e+06
total_acc,42506.0,22.124406,11.592811,1.00,13.000000,20.000000,29.000000,9.000000e+01
out_prncp,42535.0,0.000000,0.000000,0.00,0.000000,0.000000,0.000000,0.000000e+00
out_prncp_inv,42535.0,0.000000,0.000000,0.00,0.000000,0.000000,0.000000,0.000000e+00
total_pymnt,42535.0,12020.265657,9094.736121,0.00,5465.685189,9682.251696,16427.850065,5.888647e+04
total_pymnt_inv,42535.0,11312.805189,9038.544854,0.00,4793.115000,8956.080000,15544.335000,5.856368e+04
total_rec_prncp,42535.0,9675.675936,7105.750304,0.00,4400.000000,8000.000000,13499.995000,3.500002e+04
total_rec_int,42535.0,2239.981444,2585.057393,0.00,657.100000,1339.160000,2803.090000,2.388647e+04
total_rec_late_fee,42535.0,1.516890,7.830064,0.00,0.000000,0.000000,0.000000,2.090000e+02
recoveries,42535.0,103.091480,736.104640,0.00,0.000000,0.000000,0.000000,2.962335e+04
collection_recovery_fee,42535.0,14.401525,162.221310,0.00,0.000000,0.000000,0.000000,7.002190e+03
last_pymnt_amnt,42535.0,2613.245652,4385.066535,0.00,211.050000,528.360000,3170.220000,3.611520e+04
collections_12_mths_ex_med,42390.0,0.000000,0.000000,0.00,0.000000,0.000000,0.000000,0.000000e+00
mths_since_last_major_derog,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
policy_code,42535.0,1.000000,0.000000,1.00,1.000000,1.000000,1.000000,1.000000e+00
annual_inc_joint,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...
total_bc_limit,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
total_il_high_credit_limit,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
revol_bal_joint,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
sec_app_earliest_cr_line,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
sec_app_inq_last_6mths,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
sec_app_mort_acc,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
sec_app_open_acc,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
sec_app_revol_util,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
sec_app_open_act_il,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
sec_app_num_rev_accts,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
sec_app_chargeoff_within_12_mths,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
sec_app_collections_12_mths_ex_med,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
sec_app_mths_since_last_major_derog,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
hardship_type,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
hardship_reason,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
hardship_status,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
deferral_term,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
hardship_amount,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
hardship_start_date,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
hardship_end_date,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
payment_plan_start_date,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
hardship_length,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
hardship_dpd,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
hardship_loan_status,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
orig_projected_additional_accrued_interest,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
hardship_payoff_balance_amount,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
hardship_last_payment_amount,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
settlement_amount,160.0,4271.925000,3119.502707,193.29,1842.750000,3499.350000,5701.100000,1.479820e+04
settlement_percentage,160.0,49.902375,15.565995,10.69,40.000000,49.970000,60.652500,9.274000e+01
settlement_term,160.0,1.262500,4.142869,0.00,0.000000,0.000000,0.000000,2.400000e+01

There are total 42542 rows and quite a few features does not have a non-null values at all. I am going to delete those columns that have too many nulls.

In [8]:
df = df.dropna(thresh=len(df)*0.5,axis=1)

In [11]:
df.select_dtypes(include='O').describe().T

                      count unique                 top   freq
term                  42535      2           36 months  31534
int_rate              42535    394              10.99%    970
grade                 42535      7                   B  12389
sub_grade             42535     35                  B3   2997
emp_title             39909  30658             US Army    139
emp_length            41423     11           10+ years   9369
home_ownership        42535      5                RENT  20181
verification_status   42535      3        Not Verified  18758
issue_d               42535     55              Dec-11   2267
loan_status           42535      4          Fully Paid  34116
pymnt_plan            42535      1                   n  42535
desc                  29242  28963                        225
purpose               42535     14  debt_consolidation  19776
title                 42522  21256  Debt Consolidation   2259
zip_code              42535    837               100xx    649
addr_state            42535     50                  CA   7429
earliest_cr_line      42506    530              Oct-99    393
revol_util            42445   1119                  0%   1070
initial_list_status   42535      1                   f  42535
last_pymnt_d          42452    112              Mar-13   1070
last_credit_pull_d    42531    135              Oct-18   9087
application_type      42535      1          Individual  42535
hardship_flag         42535      1                   N  42535
disbursement_method   42535      1                Cash  42535
debt_settlement_flag  42535      2                   N  42375

Notice there are some features only having one value. Those should be dropped as well.

In [13]:
# Drop columns that have one unique value
df = df.loc[:,df.apply(lambda x:x.nunique() != 1)]
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 42542 entries, 0 to 42541
Data columns (total 44 columns):
loan_amnt                  42535 non-null float64
funded_amnt                42535 non-null float64
funded_amnt_inv            42535 non-null float64
term                       42535 non-null object
int_rate                   42535 non-null object
installment                42535 non-null float64
grade                      42535 non-null object
sub_grade                  42535 non-null object
emp_title                  39909 non-null object
emp_length                 41423 non-null object
home_ownership             42535 non-null object
annual_inc                 42531 non-null float64
verification_status        42535 non-null object
issue_d                    42535 non-null object
loan_status                42535 non-null object
desc                       29242 non-null object
purpose                    42535 non-null object
title                      42522 non-null object
zip_code                   42535 non-null object
addr_state                 42535 non-null object
dti                        42535 non-null float64
delinq_2yrs                42506 non-null float64
earliest_cr_line           42506 non-null object
inq_last_6mths             42506 non-null float64
open_acc                   42506 non-null float64
pub_rec                    42506 non-null float64
revol_bal                  42535 non-null float64
revol_util                 42445 non-null object
total_acc                  42506 non-null float64
total_pymnt                42535 non-null float64
total_pymnt_inv            42535 non-null float64
total_rec_prncp            42535 non-null float64
total_rec_int              42535 non-null float64
total_rec_late_fee         42535 non-null float64
recoveries                 42535 non-null float64
collection_recovery_fee    42535 non-null float64
last_pymnt_d               42452 non-null object
last_pymnt_amnt            42535 non-null float64
last_credit_pull_d         42531 non-null object
acc_now_delinq             42506 non-null float64
delinq_amnt                42506 non-null float64
pub_rec_bankruptcies       41170 non-null float64
tax_liens                  42430 non-null float64
debt_settlement_flag       42535 non-null object
dtypes: float64(24), object(20)
memory usage: 14.3+ MB

#### Now, the number of columns is cut down from 145 to 44. I am going to look at the meta data and to understand what those features are. This loan data file contains the complete information of the loans, including the current status of loans and last payment, so I need to drop those variables that only make sense after loans are approved.

### I need to go back to the meta data file with the remaining variables. I copied the list of columns above into excel and used the function, VLOOKUP, to find the explanations.

![image](/image.png)